### PR TITLE
Implement h-feed-simple tests

### PR DESCRIPTION
**Pull request by pstuifzand**
- Cleanup the date from the datetime attribute
- Trim the whitespace in the right way

### CODE REVIEW

**Comment by willnorris** [comment]
I'm pretty sure we're already trimming whitespace the right way.  From http://microformats.org/wiki/microformats2-parsing#parsing_an_e-_property (emphasis added):

> return a dictionary with two keys:
>  - html: the innerHTML of the element by using the HTML spec: Serializing HTML Fragments algorithm, **with leading/trailing whitespace removed.**
>  - value: the textContent of the element after:
>    - dropping any nested <script> & <style> elements;
>    - replacing any nested  elements with their alt attribute, if present; otherwise their src attribute, if present, adding a space at the beginning and end, resolving the URL if it’s relative;
>    - **removing all leading/trailing whitespace**
```

we should send patches to the testsuite repo to fix the test cases.

**Comment by willnorris** [comment]
I'm also pretty sure the date formatting is correct.  This looks to have been fixed in the upstream tests in https://github.com/microformats/tests/pull/89/files.  I'll pull in the latest test suite and see if they now pass.

**Comment by pstuifzand** [comment]
I created a pull request in microformats/tests#95 for the whitespace.

**Comment by willnorris** [comment]
upstream patch has been merged, so I don't think this PR is needed anymore.

**Pull request closed without merging**
